const animes = [
    {
        id: 1,
        titulo: "Nanabun no Nijyuuni",
        imagem: "img/227.jpg",
        tags: ["aventura", "drama", "fantasia", "game", "legendados",],
        lancamento: "2020",
        genero: "Musical, Slice of Life.",
        episodiosTotal: 13,
        status: "Em andamento",
        sinopse: "Naruto é uma série de anime e mangá que conta a história de Naruto Uzumaki, um jovem ninja órfão que busca reconhecimento e sonha em se tornar o Hokage, líder de sua vila. A história se passa em um mundo onde ninjas existem e lutam entre si, utilizando habilidades especiais para proteger suas vilas e cumprir missões. Naruto, com sua personalidade alegre e determinada, enfrenta desafios, faz amigos e inimigos, e descobre segredos sobre seu passado que o impulsionam em sua jornada para se tornar um grande ninja.",
        trailerUrl: "https://www.youtube.com/embed/35QdAe1AweE",
        adicionadoEm: "14 de dez de 2023 às 08:23",
        estudio: "Pierrot",
        siteOficial: "https://anime.com",
        video: "x265 10Bit",
        audio: "AAC",
        resolucao: "1080p",
        scriptOriginal: "indisponível",
        screenshots: [
            "img/55d43303b0b288ca70bbd0e73b042c2f.avif",
            "img/fsxz9pI.png",
            "img/5dca1a51a149d.webp"
        ],
        episodios: [
            { numero: 1, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 2, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 3, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 4, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 5, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 6, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 7, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 8, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
        ]
    },
    {
        id: 1,
        titulo: "Nanabun no Nijyuuni",
        imagem: "img/227.jpg",
        tags: ["aventura", "drama", "fantasia", "game", "legendados",],
        lancamento: "2020",
        genero: "Musical, Slice of Life.",
        episodiosTotal: 13,
        status: "Finalizado",
        sinopse: "Naruto é uma série de anime e mangá que conta a história de Naruto Uzumaki, um jovem ninja órfão que busca reconhecimento e sonha em se tornar o Hokage, líder de sua vila. A história se passa em um mundo onde ninjas existem e lutam entre si, utilizando habilidades especiais para proteger suas vilas e cumprir missões. Naruto, com sua personalidade alegre e determinada, enfrenta desafios, faz amigos e inimigos, e descobre segredos sobre seu passado que o impulsionam em sua jornada para se tornar um grande ninja.",
        trailerUrl: "https://www.youtube.com/embed/35QdAe1AweE",
        adicionadoEm: "14 de dez de 2023 às 08:23",
        estudio: "Pierrot",
        siteOficial: "https://anime.com",
        video: "x265 10Bit",
        audio: "AAC",
        resolucao: "1080p",
        scriptOriginal: "indisponível",
        screenshots: [
            "img/55d43303b0b288ca70bbd0e73b042c2f.avif",
            "img/fsxz9pI.png",
            "img/5dca1a51a149d.webp"
        ],
        episodios: [
            { numero: 1, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 2, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 3, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 4, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 5, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 6, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 7, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 8, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
            { numero: 9, sinopse: "Sinopse do episódio 1", downloads: { pixeldrain: "https://www.pixeldrain.com/", mega: "https://mega.io/pt-br/" } },
        ]
    },
];
